//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanara.Windows.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vanara.PInvoke.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        internal static string AccessControlTypeAllow {
            get {
                return ResourceManager.GetString("AccessControlTypeAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        internal static string AccessControlTypeDeny {
            get {
                return ResourceManager.GetString("AccessControlTypeDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDisabled {
            get {
                object obj = ResourceManager.GetObject("ArrowDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowHovered {
            get {
                object obj = ResourceManager.GetObject("ArrowHovered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowNormal {
            get {
                object obj = ResourceManager.GetObject("ArrowNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExpandoButtonV {
            get {
                object obj = ResourceManager.GetObject("ExpandoButtonV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder only.
        /// </summary>
        internal static string FileInheritance {
            get {
                return ResourceManager.GetString("FileInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder and subfolders.
        /// </summary>
        internal static string FileInheritanceCI {
            get {
                return ResourceManager.GetString("FileInheritanceCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder, subfolders and files.
        /// </summary>
        internal static string FileInheritanceCIOI {
            get {
                return ResourceManager.GetString("FileInheritanceCIOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolders only.
        /// </summary>
        internal static string FileInheritanceIOCI {
            get {
                return ResourceManager.GetString("FileInheritanceIOCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolders and files only.
        /// </summary>
        internal static string FileInheritanceIOCIOI {
            get {
                return ResourceManager.GetString("FileInheritanceIOCIOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files only.
        /// </summary>
        internal static string FileInheritanceIOOI {
            get {
                return ResourceManager.GetString("FileInheritanceIOOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder and files.
        /// </summary>
        internal static string FileInheritanceOI {
            get {
                return ResourceManager.GetString("FileInheritanceOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folders / append data.
        /// </summary>
        internal static string FileRightAppendData {
            get {
                return ResourceManager.GetString("FileRightAppendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change permissions.
        /// </summary>
        internal static string FileRightChangePermissions {
            get {
                return ResourceManager.GetString("FileRightChangePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete subfolders and files.
        /// </summary>
        internal static string FileRightDeleteSubdirectoriesAndFiles {
            get {
                return ResourceManager.GetString("FileRightDeleteSubdirectoriesAndFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traverse folder / execute file.
        /// </summary>
        internal static string FileRightExecuteFile {
            get {
                return ResourceManager.GetString("FileRightExecuteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full control.
        /// </summary>
        internal static string FileRightFullControl {
            get {
                return ResourceManager.GetString("FileRightFullControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List folder contents.
        /// </summary>
        internal static string FileRightListFolderContents {
            get {
                return ResourceManager.GetString("FileRightListFolderContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string FileRightModify {
            get {
                return ResourceManager.GetString("FileRightModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string FileRightRead {
            get {
                return ResourceManager.GetString("FileRightRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read &amp; execute.
        /// </summary>
        internal static string FileRightReadAndExecute {
            get {
                return ResourceManager.GetString("FileRightReadAndExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read attributes.
        /// </summary>
        internal static string FileRightReadAttributes {
            get {
                return ResourceManager.GetString("FileRightReadAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List folder / read data.
        /// </summary>
        internal static string FileRightReadData {
            get {
                return ResourceManager.GetString("FileRightReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read extended attributes.
        /// </summary>
        internal static string FileRightReadExtendedAttributes {
            get {
                return ResourceManager.GetString("FileRightReadExtendedAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read permissions.
        /// </summary>
        internal static string FileRightReadPermissions {
            get {
                return ResourceManager.GetString("FileRightReadPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read, write &amp; execute.
        /// </summary>
        internal static string FileRightReadWriteAndExecute {
            get {
                return ResourceManager.GetString("FileRightReadWriteAndExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special permissions.
        /// </summary>
        internal static string FileRightSpecial {
            get {
                return ResourceManager.GetString("FileRightSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string FileRightWrite {
            get {
                return ResourceManager.GetString("FileRightWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write attributes.
        /// </summary>
        internal static string FileRightWriteAttributes {
            get {
                return ResourceManager.GetString("FileRightWriteAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create files / write data.
        /// </summary>
        internal static string FileRightWriteData {
            get {
                return ResourceManager.GetString("FileRightWriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write extended attributes.
        /// </summary>
        internal static string FileRightWriteExtendedAttributes {
            get {
                return ResourceManager.GetString("FileRightWriteExtendedAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string InheritedFromNone {
            get {
                return ResourceManager.GetString("InheritedFromNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Object.
        /// </summary>
        internal static string InheritedFromParent {
            get {
                return ResourceManager.GetString("InheritedFromParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key only.
        /// </summary>
        internal static string RegistryInheritance {
            get {
                return ResourceManager.GetString("RegistryInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key and subkeys.
        /// </summary>
        internal static string RegistryInheritanceCI {
            get {
                return ResourceManager.GetString("RegistryInheritanceCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subkeys only.
        /// </summary>
        internal static string RegistryInheritanceIOCI {
            get {
                return ResourceManager.GetString("RegistryInheritanceIOCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write DAC.
        /// </summary>
        internal static string RegistryRightChangePermissions {
            get {
                return ResourceManager.GetString("RegistryRightChangePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Link.
        /// </summary>
        internal static string RegistryRightCreateLink {
            get {
                return ResourceManager.GetString("RegistryRightCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Subkey.
        /// </summary>
        internal static string RegistryRightCreateSubKey {
            get {
                return ResourceManager.GetString("RegistryRightCreateSubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerate Subkeys.
        /// </summary>
        internal static string RegistryRightEnumerateSubKeys {
            get {
                return ResourceManager.GetString("RegistryRightEnumerateSubKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        internal static string RegistryRightNotify {
            get {
                return ResourceManager.GetString("RegistryRightNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Value.
        /// </summary>
        internal static string RegistryRightQueryValues {
            get {
                return ResourceManager.GetString("RegistryRightQueryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Control.
        /// </summary>
        internal static string RegistryRightReadControl {
            get {
                return ResourceManager.GetString("RegistryRightReadControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Value.
        /// </summary>
        internal static string RegistryRightSetValue {
            get {
                return ResourceManager.GetString("RegistryRightSetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Owner.
        /// </summary>
        internal static string RegistryRightTakeOwnership {
            get {
                return ResourceManager.GetString("RegistryRightTakeOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SmallSecurity {
            get {
                object obj = ResourceManager.GetObject("SmallSecurity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SmallSecurityDisabled {
            get {
                object obj = ResourceManager.GetObject("SmallSecurityDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object.
        /// </summary>
        internal static string StdInheritance {
            get {
                return ResourceManager.GetString("StdInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object and containers.
        /// </summary>
        internal static string StdInheritanceCI {
            get {
                return ResourceManager.GetString("StdInheritanceCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object, inherited object and containers.
        /// </summary>
        internal static string StdInheritanceCIOI {
            get {
                return ResourceManager.GetString("StdInheritanceCIOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited containers.
        /// </summary>
        internal static string StdInheritanceIOCI {
            get {
                return ResourceManager.GetString("StdInheritanceIOCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited containers/objects.
        /// </summary>
        internal static string StdInheritanceIOCIOI {
            get {
                return ResourceManager.GetString("StdInheritanceIOCIOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited objects.
        /// </summary>
        internal static string StdInheritanceIOOI {
            get {
                return ResourceManager.GetString("StdInheritanceIOOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object and inherited objects.
        /// </summary>
        internal static string StdInheritanceOI {
            get {
                return ResourceManager.GetString("StdInheritanceOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string StdRightDelete {
            get {
                return ResourceManager.GetString("StdRightDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        internal static string StdRightSynchronize {
            get {
                return ResourceManager.GetString("StdRightSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take ownership.
        /// </summary>
        internal static string StdRightTakeOwnership {
            get {
                return ResourceManager.GetString("StdRightTakeOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string TaskRightExecute {
            get {
                return ResourceManager.GetString("TaskRightExecute", resourceCulture);
            }
        }
    }
}
