using System;
using System.Runtime.InteropServices;
using System.Text;
using Vanara.InteropServices;
using FILETIME = System.Runtime.InteropServices.ComTypes.FILETIME;

namespace Vanara.PInvoke
{
	public static partial class Kernel32
	{
		/*	AccessCheck
			AccessCheckAndAuditAlarmW
			AccessCheckByType
			AccessCheckByTypeAndAuditAlarmW
			AccessCheckByTypeResultList
			AccessCheckByTypeResultListAndAuditAlarmByHandleW
			AccessCheckByTypeResultListAndAuditAlarmW
			AddAccessAllowedAce
			AddAccessAllowedAceEx
			AddAccessAllowedObjectAce
			AddAccessDeniedAce
			AddAccessDeniedAceEx
			AddAccessDeniedObjectAce
			AddAce
			AddAuditAccessAce
			AddAuditAccessAceEx
			AddAuditAccessObjectAce
			AddMandatoryAce
			AddResourceAttributeAce
			AddScopedPolicyIDAce
			AdjustTokenGroups
			AdjustTokenPrivileges
			AllocateAndInitializeSid
			AllocateLocallyUniqueId
			AreAllAccessesGranted
			AreAnyAccessesGranted
			CheckTokenCapability
			CheckTokenMembership
			CheckTokenMembershipEx
			ConvertToAutoInheritPrivateObjectSecurity
			CopySid
			CreatePrivateObjectSecurity
			CreatePrivateObjectSecurityEx
			CreatePrivateObjectSecurityWithMultipleInheritance
			CreateRestrictedToken
			CreateWellKnownSid
			CveEventWrite
			DeleteAce
			DeriveCapabilitySidsFromName
			DestroyPrivateObjectSecurity
			DuplicateToken
			DuplicateTokenEx
			EqualDomainSid
			EqualPrefixSid
			EqualSid
			FindFirstFreeAce
			FreeSid
			GetAce
			GetAclInformation
			GetAppContainerAce
			GetCachedSigningLevel
			GetFileSecurityW
			GetKernelObjectSecurity
			GetLengthSid
			GetPrivateObjectSecurity
			GetSecurityDescriptorControl
			GetSecurityDescriptorDacl
			GetSecurityDescriptorGroup
			GetSecurityDescriptorLength
			GetSecurityDescriptorOwner
			GetSecurityDescriptorOwner
			GetSecurityDescriptorSacl
			GetSidIdentifierAuthority
			GetSidLengthRequired
			GetSidSubAuthority
			GetSidSubAuthorityCount
			GetTokenInformation
			GetWindowsAccountDomainSid
			ImpersonateAnonymousToken
			ImpersonateLoggedOnUser
			ImpersonateSelf
			InitializeAcl
			InitializeSecurityDescriptor
			InitializeSid
			IsTokenRestricted
			IsValidAcl
			IsValidSecurityDescriptor
			IsValidSid
			IsWellKnownSid
			MakeAbsoluteSD
			MakeSelfRelativeSD
			MapGenericMask
			ObjectCloseAuditAlarmW
			ObjectDeleteAuditAlarmW
			ObjectOpenAuditAlarmW
			ObjectPrivilegeAuditAlarmW
			PrivilegeCheck
			PrivilegedServiceAuditAlarmW
			QuerySecurityAccessMask
			RevertToSelf
			SetAclInformation
			SetCachedSigningLevel
			SetFileSecurityW
			SetKernelObjectSecurity
			SetPrivateObjectSecurity
			SetPrivateObjectSecurityEx
			SetSecurityAccessMask
			SetSecurityDescriptorControl
			SetSecurityDescriptorDacl
			SetSecurityDescriptorGroup
			SetSecurityDescriptorOwner
			SetSecurityDescriptorRMControl
			SetSecurityDescriptorSacl
			SetTokenInformation
		*/
	}
}