#pragma warning disable IDE1006 // Naming Styles

using System;
using System.Runtime.InteropServices;
using static Vanara.PInvoke.WinMm;

namespace Vanara.PInvoke
{
	/// <summary>Items from the Vfw32.dll</summary>
	public static partial class Vfw32
	{
		/*
		CAPCONTROLCALLBACK
		CAPERRORCALLBACKA
		CAPERRORCALLBACKW
		CAPSTATUSCALLBACKA
		CAPSTATUSCALLBACKW
		CAPVIDEOCALLBACK
		CAPWAVECALLBACK
		CAPYIELDCALLBACK

		IAVIEditStream
		IAVIFile
		IAVIStream
		IAVIStreaming
		IGetFrame

		AVIBuildFilterA
		AVIBuildFilterW
		AVIClearClipboard
		AVIFileAddRef
		AVIFileCreateStream
		AVIFileCreateStreamA
		AVIFileCreateStreamW
		AVIFileEndRecord
		AVIFileExit
		AVIFileGetStream
		AVIFileInfo
		AVIFileInfoA
		AVIFileInfoW
		AVIFileInit
		AVIFileOpen
		AVIFileOpenA
		AVIFileOpenW
		AVIFileReadData
		AVIFileRelease
		AVIFileWriteData
		AVIGetFromClipboard
		AVIMakeCompressedStream
		AVIMakeFileFromStreams
		AVIMakeStreamFromClipboard
		AVIPutFileOnClipboard
		AVISaveA
		AVISaveOptions
		AVISaveOptionsFree
		AVISaveVA
		AVISaveVW
		AVISaveW
		AVIStreamAddRef
		AVIStreamBeginStreaming
		AVIStreamCreate
		AVIStreamDataSize
		AVIStreamEnd
		AVIStreamEndStreaming
		AVIStreamEndTime
		AVIStreamFindSample
		AVIStreamFormatSize
		AVIStreamGetFrame
		AVIStreamGetFrameClose
		AVIStreamGetFrameOpen
		AVIStreamInfoA
		AVIStreamInfoW
		AVIStreamIsKeyFrame
		AVIStreamLength
		AVIStreamLengthTime
		AVIStreamNearestKeyFrame
		AVIStreamNearestKeyFrameTime
		AVIStreamNearestSample
		AVIStreamNearestSampleTime
		AVIStreamNextKeyFrame
		AVIStreamNextKeyFrameTime
		AVIStreamNextSample
		AVIStreamNextSampleTime
		AVIStreamOpenFromFileA
		AVIStreamOpenFromFileW
		AVIStreamPrevKeyFrame
		AVIStreamPrevKeyFrameTime
		AVIStreamPrevSample
		AVIStreamPrevSampleTime
		AVIStreamRead
		AVIStreamReadData
		AVIStreamReadFormat
		AVIStreamRelease
		AVIStreamSampleSize
		AVIStreamSampleToSample
		AVIStreamSampleToTime
		AVIStreamSetFormat
		AVIStreamStart
		AVIStreamStartTime
		AVIStreamTimeToSample
		AVIStreamWrite
		AVIStreamWriteData
		capCaptureAbort
		capCaptureGetSetup
		capCaptureSequence
		capCaptureSequenceNoFile
		capCaptureSetSetup
		capCaptureSingleFrame
		capCaptureSingleFrameClose
		capCaptureSingleFrameOpen
		capCaptureStop
		capCreateCaptureWindowA
		capCreateCaptureWindowW
		capDlgVideoCompression
		capDlgVideoDisplay
		capDlgVideoFormat
		capDlgVideoSource
		capDriverConnect
		capDriverDisconnect
		capDriverGetCaps
		capDriverGetName
		capDriverGetVersion
		capEditCopy
		capFileAlloc
		capFileGetCaptureFile
		capFileSaveAs
		capFileSaveDIB
		capFileSetCaptureFile
		capFileSetInfoChunk
		capGetAudioFormat
		capGetAudioFormatSize
		capGetDriverDescriptionA
		capGetDriverDescriptionW
		capGetMCIDeviceName
		capGetStatus
		capGetUserData
		capGetVideoFormat
		capGetVideoFormatSize
		capGrabFrame
		capGrabFrameNoStop
		capOverlay
		capPaletteAuto
		capPaletteManual
		capPaletteOpen
		capPalettePaste
		capPaletteSave
		capPreview
		capPreviewRate
		capPreviewScale
		capSetAudioFormat
		capSetCallbackOnCapControl
		capSetCallbackOnError
		capSetCallbackOnFrame
		capSetCallbackOnStatus
		capSetCallbackOnVideoStream
		capSetCallbackOnWaveStream
		capSetCallbackOnYield
		capSetMCIDeviceName
		capSetScrollPos
		capSetUserData
		capSetVideoFormat
		CreateEditableStream
		DrawDibBegin
		DrawDibChangePalette
		DrawDibClose
		DrawDibDraw
		DrawDibEnd
		DrawDibGetBuffer
		DrawDibGetPalette
		DrawDibOpen
		DrawDibProfileDisplay
		DrawDibRealize
		DrawDibSetPalette
		DrawDibStart
		DrawDibStop
		DrawDibTime
		DrawDibUpdate
		EditStreamClone
		EditStreamCopy
		EditStreamCut
		EditStreamPaste
		EditStreamSetInfoA
		EditStreamSetInfoW
		EditStreamSetNameA
		EditStreamSetNameW
		GetOpenFileNamePreviewA
		GetOpenFileNamePreviewW
		GetSaveFileNamePreviewA
		GetSaveFileNamePreviewW
		ICAbout
		ICClose
		ICCompress
		ICCompressBegin
		ICCompressEnd
		ICCompressGetFormat
		ICCompressGetFormatSize
		ICCompressGetSize
		ICCompressorChoose
		ICCompressorFree
		ICCompressQuery
		ICConfigure
		ICDecompress
		ICDecompressBegin
		ICDecompressEnd
		ICDecompressEx
		ICDecompressExBegin
		ICDecompressExEnd
		ICDecompressExQuery
		ICDecompressGetFormat
		ICDecompressGetFormatSize
		ICDecompressGetPalette
		ICDecompressOpen
		ICDecompressQuery
		ICDecompressSetPalette
		ICDraw
		ICDrawBegin
		ICDrawChangePalette
		ICDrawEnd
		ICDrawFlush
		ICDrawGetTime
		ICDrawOpen
		ICDrawQuery
		ICDrawRealize
		ICDrawRenderBuffer
		ICDrawSetTime
		ICDrawStart
		ICDrawStartPlay
		ICDrawStop
		ICDrawStopPlay
		ICDrawSuggestFormat
		ICDrawWindow
		ICGetBuffersWanted
		ICGetDefaultKeyFrameRate
		ICGetDefaultQuality
		ICGetDisplayFormat
		ICGetInfo
		ICGetState
		ICGetStateSize
		ICImageCompress
		ICImageDecompress
		ICInfo
		ICInstall
		ICLocate
		ICOpen
		ICOpenFunction
		ICQueryAbout
		ICQueryConfigure
		ICRemove
		ICSendMessage
		ICSeqCompressFrame
		ICSeqCompressFrameEnd
		ICSeqCompressFrameStart
		ICSetState
		ICSetStatusProc
		MCIWndCanConfig
		MCIWndCanEject
		MCIWndCanPlay
		MCIWndCanRecord
		MCIWndCanSave
		MCIWndCanWindow
		MCIWndChangeStyles
		MCIWndClose
		MCIWndCreateA
		MCIWndCreateW
		MCIWndDestroy
		MCIWndEject
		MCIWndEnd
		MCIWndGetActiveTimer
		MCIWndGetAlias
		MCIWndGetDest
		MCIWndGetDevice
		MCIWndGetDeviceID
		MCIWndGetEnd
		MCIWndGetError
		MCIWndGetFileName
		MCIWndGetInactiveTimer
		MCIWndGetLength
		MCIWndGetMode
		MCIWndGetPalette
		MCIWndGetPosition
		MCIWndGetPositionString
		MCIWndGetRepeat
		MCIWndGetSource
		MCIWndGetSpeed
		MCIWndGetStart
		MCIWndGetStyles
		MCIWndGetTimeFormat
		MCIWndGetVolume
		MCIWndGetZoom
		MCIWndHome
		MCIWndNew
		MCIWndOpen
		MCIWndOpenDialog
		MCIWndOpenInterface
		MCIWndPause
		MCIWndPlay
		MCIWndPlayFrom
		MCIWndPlayFromTo
		MCIWndPlayReverse
		MCIWndPlayTo
		MCIWndPutDest
		MCIWndPutSource
		MCIWndRealize
		MCIWndRecord
		MCIWndRegisterClass
		MCIWndResume
		MCIWndReturnString
		MCIWndSave
		MCIWndSaveDialog
		MCIWndSeek
		MCIWndSendString
		MCIWndSetActiveTimer
		MCIWndSetInactiveTimer
		MCIWndSetOwner
		MCIWndSetPalette
		MCIWndSetRepeat
		MCIWndSetSpeed
		MCIWndSetTimeFormat
		MCIWndSetTimers
		MCIWndSetVolume
		MCIWndSetZoom
		MCIWndStep
		MCIWndStop
		MCIWndUseFrames
		MCIWndUseTime
		MCIWndValidateMedia
		mmioFOURCC
		StretchDIB
		*/
	}
}