namespace Vanara.PInvoke;

public static partial class Gdi32
{
	/*
	D3DKMTAbandonSwapChain		
	D3DKMTAcquireKeyedMutex		
	D3DKMTAcquireKeyedMutex2		
	D3DKMTAcquireSwapChain		
	D3DKMTAdjustFullscreenGamma		
	D3DKMTChangeVideoMemoryReservation		
	D3DKMTCheckExclusiveOwnership		
	D3DKMTCheckMonitorPowerState		
	D3DKMTCheckMultiPlaneOverlaySupport		
	D3DKMTCheckMultiPlaneOverlaySupport2		
	D3DKMTCheckMultiPlaneOverlaySupport3		
	D3DKMTCheckOcclusion		
	D3DKMTCheckSharedResourceAccess		
	D3DKMTCheckVidPnExclusiveOwnership		
	D3DKMTCloseAdapter		
	D3DKMTConfigureSharedResource		
	D3DKMTCreateAllocation		
	D3DKMTCreateAllocation2		
	D3DKMTCreateContext		
	D3DKMTCreateContextVirtual		
	D3DKMTCreateDCFromMemory		
	D3DKMTCreateDevice		
	D3DKMTCreateHwContext		
	D3DKMTCreateHwQueue		
	D3DKMTCreateKeyedMutex		
	D3DKMTCreateKeyedMutex2		
	D3DKMTCreateOutputDupl		
	D3DKMTCreateOverlay		
	D3DKMTCreatePagingQueue		
	D3DKMTCreateProtectedSession		
	D3DKMTCreateSwapChain		
	D3DKMTCreateSynchronizationObject		
	D3DKMTCreateSynchronizationObject2		
	D3DKMTDestroyAllocation		
	D3DKMTDestroyAllocation2		
	D3DKMTDestroyContext		
	D3DKMTDestroyDCFromMemory		
	D3DKMTDestroyDevice		
	D3DKMTDestroyHwContext		
	D3DKMTDestroyHwQueue		
	D3DKMTDestroyKeyedMutex		
	D3DKMTDestroyOutputDupl		
	D3DKMTDestroyOverlay		
	D3DKMTDestroyPagingQueue		
	D3DKMTDestroyProtectedSession		
	D3DKMTDestroySynchronizationObject		
	D3DKMTEnumAdapters		
	D3DKMTEnumAdapters2		
	D3DKMTEscape		
	D3DKMTEvict		
	D3DKMTFlipOverlay		
	D3DKMTFlushHeapTransitions		
	D3DKMTFreeGpuVirtualAddress		
	D3DKMTGetAllocationPriority		
	D3DKMTGetContextInProcessSchedulingPriority		
	D3DKMTGetContextSchedulingPriority		
	D3DKMTGetDeviceState		
	D3DKMTGetDisplayModeList		
	D3DKMTGetDWMVerticalBlankEvent		
	D3DKMTGetMultiPlaneOverlayCaps		
	D3DKMTGetMultisampleMethodList		
	D3DKMTGetOverlayState		
	D3DKMTGetPostCompositionCaps		
	D3DKMTGetPresentHistory		
	D3DKMTGetPresentQueueEvent		
	D3DKMTGetProcessDeviceRemovalSupport		
	D3DKMTGetProcessSchedulingPriorityClass		
	D3DKMTGetResourcePresentPrivateDriverData		
	D3DKMTGetRuntimeData		
	D3DKMTGetScanLine		
	D3DKMTGetSetSwapChainMetadata		
	D3DKMTGetSharedPrimaryHandle		
	D3DKMTGetSharedResourceAdapterLuid		
	D3DKMTInvalidateActiveVidPn		
	D3DKMTInvalidateCache		
	D3DKMTLock		
	D3DKMTLock2		
	D3DKMTMakeResident		
	D3DKMTMapGpuVirtualAddress		
	D3DKMTMarkDeviceAsError		
	D3DKMTOfferAllocations		
	D3DKMTOpenAdapterFromDeviceName		
	D3DKMTOpenAdapterFromGdiDisplayName		
	D3DKMTOpenAdapterFromHdc		
	D3DKMTOpenAdapterFromLuid		
	D3DKMTOpenKeyedMutex		
	D3DKMTOpenKeyedMutex2		
	D3DKMTOpenKeyedMutexFromNtHandle		
	D3DKMTOpenNtHandleFromName		
	D3DKMTOpenProtectedSessionFromNtHandle		
	D3DKMTOpenResource		
	D3DKMTOpenResource2		
	D3DKMTOpenResourceFromNtHandle		
	D3DKMTOpenSwapChain		
	D3DKMTOpenSynchronizationObject		
	D3DKMTOpenSyncObjectFromNtHandle		
	D3DKMTOpenSyncObjectFromNtHandle2		
	D3DKMTOpenSyncObjectNtHandleFromName		
	D3DKMTOutputDuplGetFrameInfo		
	D3DKMTOutputDuplGetMetaData		
	D3DKMTOutputDuplGetPointerShapeData		
	D3DKMTOutputDuplPresent		
	D3DKMTOutputDuplReleaseFrame		
	D3DKMTPollDisplayChildren		
	D3DKMTPresent		
	D3DKMTPresentMultiPlaneOverlay		
	D3DKMTPresentMultiPlaneOverlay2		
	D3DKMTPresentMultiPlaneOverlay3		
	D3DKMTPresentRedirected		
	D3DKMTQueryAdapterInfo		
	D3DKMTQueryAllocationResidency		
	D3DKMTQueryClockCalibration		
	D3DKMTQueryFSEBlock		
	D3DKMTQueryProcessOfferInfo		
	D3DKMTQueryProtectedSessionInfoFromNtHandle		
	D3DKMTQueryProtectedSessionStatus		
	D3DKMTQueryRemoteVidPnSourceFromGdiDisplayName		
	D3DKMTQueryResourceInfo		
	D3DKMTQueryResourceInfoFromNtHandle		
	D3DKMTQueryVideoMemoryInfo		
	D3DKMTQueryVidPnExclusiveOwnership		
	D3DKMTReclaimAllocations		
	D3DKMTReclaimAllocations2		
	D3DKMTRegisterTrimNotification		
	D3DKMTReleaseKeyedMutex		
	D3DKMTReleaseKeyedMutex2		
	D3DKMTReleaseProcessVidPnSourceOwners		
	D3DKMTReleaseSwapChain		
	D3DKMTRender		
	D3DKMTReserveGpuVirtualAddress		
	D3DKMTSetAllocationPriority		
	D3DKMTSetContextInProcessSchedulingPriority		
	D3DKMTSetContextSchedulingPriority		
	D3DKMTSetDisplayMode		
	D3DKMTSetDisplayPrivateDriverFormat		
	D3DKMTSetDodIndirectSwapchain		
	D3DKMTSetFSEBlock		
	D3DKMTSetGammaRamp		
	D3DKMTSetHwProtectionTeardownRecovery		
	D3DKMTSetMonitorColorSpaceTransform		
	D3DKMTSetProcessSchedulingPriorityClass		
	D3DKMTSetQueuedLimit		
	D3DKMTSetStablePowerState		
	D3DKMTSetSyncRefreshCountWaitTarget		
	D3DKMTSetVidPnSourceHwProtection		
	D3DKMTSetVidPnSourceOwner		
	D3DKMTSetVidPnSourceOwner1		
	D3DKMTSetVidPnSourceOwner2		
	D3DKMTSharedPrimaryLockNotification		
	D3DKMTSharedPrimaryUnLockNotification		
	D3DKMTShareObjects		
	D3DKMTSignalSynchronizationObject		
	D3DKMTSignalSynchronizationObject2		
	D3DKMTSignalSynchronizationObjectFromCpu		
	D3DKMTSignalSynchronizationObjectFromGpu		
	D3DKMTSignalSynchronizationObjectFromGpu2		
	D3DKMTSubmitCommand		
	D3DKMTSubmitCommandToHwQueue		
	D3DKMTSubmitPresentBltToHwQueue		
	D3DKMTSubmitSignalSyncObjectsToHwQueue		
	D3DKMTSubmitWaitForSyncObjectsToHwQueue		
	D3DKMTTrimProcessCommitment		
	D3DKMTUnlock		
	D3DKMTUnlock2		
	D3DKMTUnregisterTrimNotification		
	D3DKMTUpdateAllocationProperty		
	D3DKMTUpdateGpuVirtualAddress		
	D3DKMTUpdateOverlay		
	D3DKMTWaitForIdle		
	D3DKMTWaitForSynchronizationObject		
	D3DKMTWaitForSynchronizationObject2		
	D3DKMTWaitForSynchronizationObjectFromCpu		
	D3DKMTWaitForSynchronizationObjectFromGpu		
	D3DKMTWaitForVerticalBlankEvent		
	D3DKMTWaitForVerticalBlankEvent2		
	*/
}
