namespace Vanara.PInvoke
{
	/// <summary>Items from the Msi.dll</summary>
	public static partial class Msi
	{
		/*
		MsiCreateRecord
		MsiCreateTransformSummaryInfo
		MsiDatabaseApplyTransform
		MsiDatabaseCommit
		MsiDatabaseExport
		MsiDatabaseGenerateTransform
		MsiDatabaseGetPrimaryKeys
		MsiDatabaseImport
		MsiDatabaseIsTablePersistent
		MsiDatabaseMerge
		MsiDatabaseOpenView
		MsiDoAction
		MsiEnableUIPreview
		MsiEnumComponentCosts
		MsiEvaluateCondition
		MsiFormatRecord
		MsiGetActiveDatabase
		MsiGetComponentState
		MsiGetDatabaseState
		MsiGetFeatureCost
		MsiGetFeatureState
		MsiGetFeatureValidStates
		MsiGetLanguage
		MsiGetLastErrorRecord
		MsiGetMode
		MsiGetProperty
		MsiGetSourcePath
		MsiGetSummaryInformation
		MsiGetTargetPath
		MsiOpenDatabase
		MsiPreviewBillboard
		MsiPreviewDialog
		MsiProcessMessage
		MsiRecordClearData
		MsiRecordDataSize
		MsiRecordGetFieldCount
		MsiRecordGetInteger
		MsiRecordGetString
		MsiRecordIsNull
		MsiRecordReadStream
		MsiRecordSetInteger
		MsiRecordSetStream
		MsiRecordSetString
		MsiSequence
		MsiSetComponentState
		MsiSetFeatureAttributes
		MsiSetFeatureState
		MsiSetInstallLevel
		MsiSetMode
		MsiSetProperty
		MsiSetTargetPath
		MsiSummaryInfoGetProperty
		MsiSummaryInfoGetPropertyCount
		MsiSummaryInfoPersist
		MsiSummaryInfoSetProperty
		MsiVerifyDiskSpace
		MsiViewClose
		MsiViewExecute
		MsiViewFetch
		MsiViewGetColumnInfo
		MsiViewGetError
		MsiViewModify
		*/
	}
}